### ISSUE TITLE
Missing renewable generators in prod_p

### ISSUE THREAD

**Issue by marota** [mjothy/ChroniX2Grid#13] opened 2020-06-12 16:51 UTC
SOme runs of chronix2grid lead to missing renewable generators in prod_p, which raises an error when loading with Grid2op

**Comment by camiloromers** [comment] 2020-06-12 17:39
To reproduce it just run the following
```
chronix2grid --mode LRT --input-folder input_data --ignore-warnings --weeks 4 --case case118_l2rpn_neurips_3x --n_scenarios 4 --nb_core 4 --scenario_name july --start-date 2012-07-01 --seed-for-loads 1609097239 --seed-for-res 1609097239 --seed-for-dispatch 1609097239
```

**Comment by vinault** [comment] 2020-06-14 20:15
Hi Camilo, 

I couldn't find the case case118_l2rpn_neurips_3x so I tested with case118_l2rpn_neurips_3x_renew. Generation was successful and I then was able to execute the notebook running_chronics_grid2op.ipynb all the way.

@marota you mention an error when loading with Grid2op, can you provide a way to reproduce the error.
@camiloromers does the command you provided raise an error ? Which one ? If so, it's not the same problem as @marota.

On a side note, I found some issue running the kpis because the renewable ninja wind csv file parameter was not updated with the last case.

**Comment by marota** [comment] 2020-06-15 07:34
We are talking about the same problem. The scenario july_03 raised an error when running_grid2op because of missing generators.
I will try to reproduce also loacally on my side (this was done on AWS)

**Comment by camiloromers** [comment] 2020-06-15 09:12
Hello @vinault, yup you can use `case118_l2rpn_neurips_3x_renew`. I reproduced the error locally. To have same output, can u replace key `grid_path` in the attached json file with your respective grid location please. Then I typed the following:

```
chronix2grid --mode LRT --input-folder input_data/ --weeks 4 --case case118_l2rpn_neurips_3x_renew --n_scenarios 4 --nb_core 4 --scenario_name july --start-date 2012-07-01 --seed-for-loads 1609097239 --seed-for-res 1609097239 --seed-for-dispatch 1609097239
```
[params_opf.json.zip](https://github.com/mjothy/ChroniX2Grid/files/4779199/params_opf.json.zip)

**Comment by vinault** [comment] 2020-06-15 09:53
Hi @camiloromers, the grid_path key of params_opf.json is not used anymore.
Also, i'm afraid I cannot reproduce your error. 
I'm linking a screenshot where you can see that the Scenario_july_3 has 62 generators on my side.

![image](https://user-images.githubusercontent.com/25577263/84643947-c5b32680-aefe-11ea-9d49-7e80d600abd0.png)

**Comment by camiloromers** [comment] 2020-06-15 11:37
It's totally weird. Can u use the following case please and try to run the same thing please?
[case118_l2rpn_neurips_3x_renew_modifySlackBeforeChronixGeneration.zip](https://github.com/mjothy/ChroniX2Grid/files/4779944/case118_l2rpn_neurips_3x_renew_modifySlackBeforeChronixGeneration.zip)

**Comment by vinault** [comment] 2020-06-15 12:03
I was able to reproduce the bug on this particular case so I'll get into it. Thanks @camiloromers

**Comment by vinault** [comment] 2020-06-15 14:15
So, after going through the log one more time I realized that the OPF fails for the third scenario so that the missing columns in prod_p.csv.bz2 (corresponding to hydro, thermal and nuclear) is expected.

Can you confirm it also fails on your side @camiloromers ?

**Comment by vinault** [comment] 2020-06-16 12:55
The OPF failing is confirm. This is not a ChroniX2Grid issue. I close the issue.

**Closed by vinault** 2020-06-16 12:55 UTC
Labels: bug
